### ISSUE TITLE
git cache and public repository error in bad network

### ISSUE THREAD

**Issue by LeoDT** [Hacklone/private-bower#156]
I'm in a bad netword situation, so git clone github/xxx/xxx may fail or timeout. but the public package infomation has saved in the repository file. so I must delete it and try again.

I think the package should write into the file after git clone finished?

**Comment by spoco2** [comment]
Yeah, similar issue here. Although I think this happens even when there's no 'timeout' as such, it can happen even when it just takes a while for the package to download.

The web interface will show the package, but with no information, bower install will fail because it can't resolve any information... 

It needs to handle things better in regards to taking time to download packages. 

Initial startup of an instance of private-bower seems to need a number of calls to it before it's finally loaded and cached the content.

This is when I'm setting it to locally cache content within its own git repo, because that's the behaviour we want from it.

It does work after calling it a number of times though, it finally pulls down the packages.
