### ISSUE TITLE
It doesn't fallback to public packages

### ISSUE THREAD

**Issue by hendiko** [Hacklone/private-bower#179]
I installed private-bower following this [post](https://github.com/Hacklone/private-bower/wiki/Installing%20on%20Ubuntu), I used sample configuration to start the private bower, it runs well but it doesn't fallback to public packages.

```
$ bower search jquery
No results.
```

When I search a package that doesn't exist in my private registry, it just return "No results".

**Comment by d3spis3d** [comment]
I experienced the same issue. I got around it by adding the public bower repository to the .bowerrc config file. E.g.

    {
        "registry": {
            "search": [
                "http://private-bower-here:5678",
                "http://bower.herokuapp.com"
            ]
        }
    }

**Comment by krysalead** [comment]
Hi,

I got the same issue, it was working very well, then it fails to 
bower ENOTFOUND     Package moment not found
on every package.
I am using the default configuration provided on the wiki.
I have reinstalled the private-bower
I have started as a daemon (macosX)
I have started it manually
Removed the bowerRepository files
I will try to add the fallback into the bowerrc file but having this fallback on the server is quite convenient.
Otherwise it is a greate tool ! thanks

**Comment by daniel-rosiak** [comment]
Same issue here. Seems just noticed it today.

**Comment by ow--** [comment]
Something might have changed in the hosting environment of the public registry since /packages/ doesn't resolve to the [registered route /packages](/bower/registry). Removing the trailing / in the config worked for me.

**Comment by devlz303** [comment]
Same over here. The solution @ow--  mentions (remove the traling / in the private bower config) is working for me too.

**Comment by jstoja** [comment]
@Hacklone Can you merge this ? Several people encountered the same problem :)

**Comment by sanbor** [comment]
I copy-pasted the example in http://hacklone.github.io/private-bower/#config-file and it had the trailing `/`. Luckily I found this issue. :)
